version: '3'

services:
## python3 
  python3:
    restart: always
    build:
      context: .
      dockerfile: ./python/Dockerfile
    container_name: "python_culc"
    working_dir: "/root/src"
    tty: true
    volumes:
      - ./python:/root/src
    #networks:
      #- 