version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "minimal-gpu"
    working_dir: "/app"
    volumes:
      - ./src:/app/src:ro
      - ./data:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: "no"

networks:
  default:
    driver: bridge
